README.md

Fixes #24 
Contributor section added. This section will automatically include new contributor images whenever their pull requests are merged. 
Also added one screenshot of the inital form page of the website

Enhance README.md as per issue #24

---

index.html
script.js
style.css

Hi, @sk66641 I have added theme changing feature. Please review it. #55

theme toggle added

---

index.html
style.css

The form can now be viewed completely without scrolling it down
closes: #185 
Before fixing:
After fixing:

The size of the container is fixed

---

script.js

Hey @sk66641 ,
issue closes #223 
I have resolved the issue to persist the dark mode preference across page refreshes using localStorage.
The changes ensure that the user's selected mode (dark or light) is maintained even after the page is refreshed.
**Changes made are as follows :**
Added functionality to check "localStorage" for the user's dark mode preference upon page load and set the initial state accordingly.
Updated the event listener for the toggle switch to save the dark mode preference in localStorage whenever the user changes the mode.
Now, Whenever user will refresh or log in the page again, The selected mode preference will be the same as chosen.
Please take a look and review it.
Also, please add the labels.

Resolved dark-mode persist issue

---

pages/feedback.html

added the back to top button and fixed the title of the feedback page
Fixes #370 
Fixes #371

added back to top button and fixed the title of the feedback page

---

404.html
css/404.css
css/about.css
css/features.css
css/feedback.css
css/style.css
index.html
pages/about.html
pages/features.html
pages/feedback.html

Updated Footer Section

---

css/style.css
index.html
js/script.js

Changes: 
- Added an add time modal, decreased the blur during this specific modal so user can see the current counter value too
- Added remember state so that if the simulation was paused before add time, it remains that way with just an updated counter value
- Added success and fail notifs with proper css and separate showSuccess() showFail() functions so they can be added in other places too if needed
- Added the "add time" statement in the modal that shows up at start of simulation 
- Commented properly
Fixes:  #380

Addtime alerts

---

css/style.css

changed the ui of the warning modals
all the 3 warning modals ui has been changed
Fixes:  #406

[Feature]: ui enhancement 

---

index.html

The input fields 1,3,5,6 are marked with Red Asterisk as they are the mandatory fields. 
This enhances the project usability.
No change in dependencies.
Fixes:  #287

All the Necessary fields are marked with Red Asterisk

---

css/style.css

Earlier the width of the FAQ box was looking weird for smaller mobile devices, I fixed it.
Fixes:  #428
Before change:
After change:

FAQ box width fixed

---

pages/privacy.html
pages/terms.html

Prior to this change, there was no way to switch to light mode in the privacy-policy page (/pages/privacy.html) and terms-and-conditions page (/pages/terms.html)
Fixes:  #427

Added mode toggler in privacy policy and Terms page

---

css/about.css

Hey @sk66641 and @aditya-bhaumik 
- issue closes #494 
I have removed unnecessary extra spaces above contributors page in mobile view

Removed Unnecessary Extra Spaces above Contributors Page in Mobile View

---

Login/script1.js

This change addresses an issue where the password toggle functionality fails when the required elements (password input fields or toggle buttons) are missing from the DOM. The script has been updated to include null checks before manipulating these elements, ensuring that the rest of the page continues to function even if these elements are not present. Additionally, this update refactors the code to adhere to the DRY (Don't Repeat Yourself) principle and provides more robust form validation.
Fixes:  #506 
N/A

Fix Password Toggle Functionality and Enhance Form Validation

---

404.html
css/404.css
css/style.css
index.html
js/404.js
pages/privacy.html
pages/terms.html

I have removed the code for the old theme toggle and added the new one in styles.css file
Replaced the toggle in privacy and terms pages, however i did not add the toggle to the pages where it was absent because it might've been with another existing open issue, but let me know if the same is supposed to be covered under my issue only
Fixes:  #511

Different theme slider

---

index.html
js/script.js

Added modals for  both saving and loading presets,
Edited notification popups such that they display the message passed in the function as the text of the notif
Added fail/success notifications whereever necessary in the preset process
Fixes: 
Issue #516 
Issue #518 
[I made the changes in the same branch because i forgot i made two separate issues for it, if you could adjust the level accordingly ill be extremely grateful, thankyou!]
- [x I have performed a self-review of my own code

Preset Modals and Notifications

---

css/style.css
index.html
js/backToTopBtn.js
js/script.js
pages/about.html
pages/contributors.html
pages/faq.html
pages/features.html
pages/feedback.html
pages/privacy.html
pages/terms.html

Updated the backtotop js file completely and added code and listeners that do not cause issues in the console and get executed smoothly without fail tested on all pages and ensured that button is hidden during loading and simulation
Added function that is disabled (hidden) on zero scroll on all pages 
Removed pointless css added in each of the side pages for a minor thing (bottom spacing) so improved it by adding a separate div name on main page (hence the number of reduced lines of code) and also loading time decreased after these changes considerably
Fixes:  #515 
kindly consider updating level thank youu

Back to top button

---

js/theme.js

fixing default state of slider in theme.js 
little error on my part in pr 538 for issue #535

saved state of theme toggle

---

index.html

Reverts sk66641/Random-Disco-Light-Simulator#540

Revert "Removing unnecessary code from index.html"

---

css/backToTopButton.css

I have fixed the overlapping of back to top button with other icons in every page of the website .
Fixes:  #547

Fixed the overlapping of back to top button with other icons .

---

pages/privacy.html
pages/terms.html

Hey @sk66641 @aditya-bhaumik 
issue closes #556 
I have implemented a dynamic "Last Updated" date feature for the legal pages on the website, including the Terms and Conditions and Privacy Policy pages.
The **date format** is set to **"month day, year"** and will update dynamically to reflect the current date. 
**Additionally, each page has a specific update frequency to ensure the date remains accurate.**
**Changes Made :** 
Added a script to dynamically update the "Last Updated" date for the Terms and Conditions, Privacy Policy, and Licensing pages.
The date format is "month day, year" for a professional appearance.
**Here -**

✔️Added Dynamic "Last Updated" Functionality to All Legal Pages !

---

README.md

I changes Readme File 
Fixes:  #(issue no.)
#564

Fixes #564

---

404.html
css/preloader.css
index.html
pages/about.html
pages/contributors.html
pages/faq.html
pages/features.html
pages/feedback.html
pages/privacy.html
pages/terms.html

Hey @aditya-bhaumik @sk66641 
- issue fixes #563
I have added a preloader integrated with a load of percentage to all pages (excluding homepages)
- Added Preloaer which is a gradient of spinner `#ff2d15`, `#be18ff`, `#0d3dff`
- Integrated loader with `Percentage indicator: 0% to 100%` | Color gradient of `#be18ff`, `#ffffff`
- Added logic to display the preloader and update the loading percentage.
- Ensured the preloader hides and the content displays once loading is complete.
- Integrated in all pages
- Positioned in the center with `z-index: 9999;` to ensure it stays above.
https://github.com/user-attachments/assets/733197ae-c379-4da3-af22-32cecb514695

Add "Preloader" to All Pages (excluding Homepage) 

---

404.html
css/preloader.css
js/preloader.js
js/script.js
pages/about.html
pages/contributors.html
pages/faq.html
pages/features.html
pages/feedback.html
pages/licensing.html
pages/privacy.html
pages/terms.html

The particle and snowflake effect has been fixed in all the side pages.
The issue was that the preloader.css file had "display none" for the content that affected the particle effect, and the snowflake effect was preceeded by warning modal in script.js so that cause error in console.
Ive made a separate file for the preloader js and added the snowflake function in it so that all the pages have the preloader as well as the snowflake thing
Fixes:  #591

Fixed preloader bug

---

pages/contributors.html

Hey @sk66641 @aditya-bhaumik 
issue closes #536 
- I have **added the Diagonal Effect on Hovering** on each contributors card
- Also **Added Transitional Text Shadows to the `Contributors-name` and `Github-Contributions` info**
- **Added "Img Border" On hover** to make focus on it.
- **Followed the website theme for it.**
- **It Works in both Dark and Light Mode** Very Well !
- Earlier the texts on the card were not visible properly.
- I also **made the Page "Responsive" for all screen sizes.**
**BEFORE**
**AFTER: **
Please take a look - 
https://github.com/user-attachments/assets/0ac9019b-4811-4d71-93aa-f88e06d2dd1b

✔️Added Diagonal-Hovering Effect to Each Card!

---

css/style.css
index.html
js/script.js

the addition of icons creates a uniformity in structure and looks aesthetically pleasing
Fixes:  #606

adding icons to side bar

---

Login/index1.html
Login/script1.js
Login/styles1.css

added captcha to the login page

---

pages/about.html
pages/faq.html
pages/feedback.html
pages/privacy.html
pages/terms.html

added the aria labels for all the pages which were missing it

---

index.html
js/script.js

the issue was that the pause was in span class which had overwriting styles so i removed it and adjusted js accordingly
Fixes:  #634

Fixing pause font
