sk66641/Random-Disco-Light-Simulator

- index.html
- style.css
Fixed issue: #7 
@sk66641 Thanks for assigning me for this beautiful project.
Here what I changed in this PR:
I designed the main page with more attractive colors, background-colors, font-sizes etc. I made input fields and labels more beautiful. You can compare the project by seeing these attached screenshots:
Screenshot(Before my work):
Screenshot(After my work):
@sk66641 Please review the code changes and merge this PR.
Thankyou!
> Enhanced page UI which is more attractive than previous.

- .vscode/settings.json
- index.html
- script.js
- style.css
Fixes #23 
Created a new input field in the inital form for the user to enter the countdown duration in seconds
Added a visible timer display that shows the countdown at the top right corner of the screen when we start the simulation
Added the logic to start the countdown when the simulation begins. Ensure the timer accurately counts down and updates the display.
Integrated the function to stop the light simulation when the timer reaches zero. Reset the screen to the initial form once the timer ends
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/92214013/cb6a82fd-a2cb-4d2a-98f9-6d78953d3857
> [Feature] : Implement Countdown Timer to Control Disco Light Duration

- .github/workflows/autocomment-issue.yml
Fixes #13 
@sk66641 please review and merge this PR 
Also, please add the 'gssoc' and level labels and assign this PR to me
Thank you!
> added workflow as per issue #13

- .github/workflows/autocomment-pr-raise.yml
Fixes #14 
@sk66641 please review and merge this PR
Also, please add the 'gssoc' and level labels and assign this PR to me
Thank you!
> added workflow as per issue #14

- .github/workflows/autocomment-pr-merge.yml
Fixes #15 
@sk66641 please review and merge this PR
Also, please add the 'gssoc' and level labels and assign this PR to me
Thank you!
> added workflow as per issue #15

- .github/workflows/autocomment-iss-close.yml
Fixes #16 
@sk66641 please review and merge this PR
Also, please add the 'gssoc' and level labels and assign this PR to me
Thank you!
> added workflow as per issue #16

- index.html
- style.css
I have made the website fully responsive, fixed some UI issues, and improved the overall look of the website.
Issue: #42 
Before:
After:
Before:
After:
> made responsive and fixed other ui issues

- background.js
- index.html
- script.js
- style.css
I have used particle.js to make the stars move in the background giving the website a much more dynamic feel.
Here is the video of the changes i have made- (the flickering is recordings fault , its not there in the final output)
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/117587914/7f73ce2f-eeed-4d61-8a3d-85901ff33d9e
> updated background #59

- script.js
I added the incorrect field and its correction in the error text message.
Some images added for reference -
1]
2]
3] For two or more fields having an input error.
Please review and let me know if any changes are required @sk66641.
GSSoC'24
> Update script.js - Issue : To enhance user experience by specifying the incorrect field in error text.

- style.css
I have fixed the issue no #76 
The header was getting cutting off from chrome , some header text were hidden behind chrome . Used vw and vh so its element will not overflow and also making it responsive ,if you want any changes just tag me in message
> fixed cutting header

- index.html
- script.js
- style.css
Fixes #78 
I made the changes as requested and also fixed the problem i was facing in #89 The only update i made is i decided to keep the sound effects in the form also so that the user gets to select a initial song or when they cant decide on a music they can just randomize the option using the button
I have resolved all the conflicts which i had in #89 
@sk66641 please review this pull request and merge this pull request under gssoc'24
> [Feature] : Music Selection Dropdown during the simulation

- index.html
- style.css
Hey @sk66641 ,
i added comment button for user give reviews about disco light ..
user click on comment button then open the comment form and submit
> comment section added

- script.js
- style.css
This pull request addresses issue #90 by implementing dynamic particle animation using the particle.js library in the Disco Light Simulator. The enhancement enriches the visual experience of the simulator by introducing vibrant, interactive particle effects that respond to user interactions. By integrating dynamic particle animations, this feature elevates the immersive quality of the simulator, captivating users' attention and enhancing their overall experience.
Issue #90
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/109781385/8d0b63d5-658c-42d5-8b68-30cffc712ca5
> Implement Dynamic Particle Animation in Disco Light Simulator

- index.html
#79 
Removed negative numbering from
1.Number of colours
2.Time interval
3.Countdown timer
> Removed negative numbering

- style.css
**Issue #104 was fixed. The result attached below :**
The timer and button's visibility was decreased. It fully visible while the user hover that.
> Issue #104 fixed

- index.html
- style.css
I changed the font-family to give it a more elegant look. And also the footer elements were previously not visible when changed to light mode, I fixed them and now we can view it in the same.
> Changed the font family and made the footer visible in light mode too 

- index.html
Closes #99
Updated the former twitter icon with the X icon.
**Test:**
The code was tested by me and it has no issues.
**Screenshot:**
**I followed the Code of Conduct and Contributing Guidelines.**
> Updated twitter icon

- CONTRIBUTING.md
- index.html
Fixes #70 
Added aria labels to improve accessibility. Updated contribution guidelines to ensure aria label addition by future contributors"
@sk66641 please review and merge this pull request under gssoc'24
> Add ARIA Labels to Improve Accessibility

- index.html
- script.js
**Issue #105 Fixed**
**Improvement : Replay option added at the end**
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/114602603/34aa06cb-f8f2-4970-8c79-3cd63548062a
> Issue 105 Fixed

- index.html
- script.js
- style.css
Fixed Issue #114 
Hey, @sk66641 I have added back to the top button which when clicked will reload to top of the page. please review it.
> back to top button added

- index.html
- script.js
- style.css
Fixes #123 
The website has undergone the following changes:
- A navbar now sits at the top of the webpage. As the width of the website decreases, a menu button will appear. Clicking this button reveals all the navbar items.
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153659573/adddc9bb-f4e4-4a5e-8aae-e959ff5da154
- The white line that previously occupied the footer has been removed.
- Additionally, when the width decreases, the gap between icons decreases, and the font size of the Copyright statement also decreases to maintain visual harmony.
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153659573/2a885a11-906c-4ca3-b66f-90ddec4cf1c4
> Fixes #123 : Made website Responsive including Header and Footer

- index.html
- script.js
- style.css
Fixes #82 
Added a new button labeled "Pause" that allows users to pause the simulation.
When the simulation is paused, the background animation and timer will stop.
Changes the button label to "Start" when the simulation is paused to indicate that clicking it will resume the simulation.
Upon clicking the "Start" button, the simulation should resume from where it was paused, with the background animation and timer continuing.
I have also made sure that the button is only visible when the required fields are filled. 
@sk66641 please review and merge this pull request
> [Feature] : Add Pause/Start Button Functionality

- script.js
fixes: #153 
I Fixed the bug by making changes to the functionality. 
Now the fields will reset to default by clicking the reset button.
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/125206920/bdcb979f-5d5b-41e7-8829-f8213193e326
> [Bug]: Reset button not working

- script.js
Fixed Issue #115  
Hey, @sk66641 I have disabled appearance of change music option before successful submission, please review it. 
Thank you.
> disabled change music before successful submission

- index.html
- style.css
Closes #158 
1. Added styles to about popup
2. Added styles to content of about popup
3. Added styles to about popup h2
4. Added styles to about popup paragraph text
5. Added more styles
6. Added text shadow for about popup
7. Update style.css
8. Update index.html
@sk66641 Please label this PR under GSSoC
> Added styles to about pop up  #158

- index.html
- script.js
- style.css
**Changes made:**
Made a new function toggleTheme() to ensure the smooth working of the toggle in sript.js, a
Added toggle in the form of checkbox in index.html (and removed already existing theme change buttons) 
Added styles in the slider in style.css.
Issue #154 
**What it look like:**
> Added theme toggle

- index.html
- style.css
Changed font color of title in light mode which is now visible both in light and dark mode.
Fixes #188 
#Screenshots
> Font color changed in light mode

- background.js
- style.css
Fixed issue #178
I have created a colourful particles background also changed the color for light mode.
BEFORE
AFTER
> Added different colour particle to the background

- index.html
Automatic copyright added
Fixed issue #198 
@sk66641 Please review my PR
> Automatic copyright added

- index.html
- style.css
hi @sk66641,
closes #205 
**Summary of Improvements:**
1. Replaced the text "Back to Top" with a visually intuitive up arrow icon using Font Awesome.
2. Applied a linear gradient background and circular shape to the button for a modern look.
3. Designed the hover effect by adding scale and shadow animations for better user interaction.
**Here is the result after Styling :**
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/131389695/4edd646a-0b12-43c8-8710-62eb3d1722f5
Could you Please Take a look and review it.
> Styled the Scroll to Top Button With Up Arrow Icon

- index.html
- style.css
Fixes Issue #168 
Hello, this is Isha Prajapati, I have completed the task of improving our website's responsiveness.
Here are the changes made:
Refactored for adaptive layouts and optimized media queries.
Enhanced for efficient resizing and smooth interactions.
Minimized CSS for better load times.
Ensured consistency across devices and browsers.
These improvements enhance the user experience and functionality across all devices.
Thank you!
> Responsiveness Across Devices

- style.css
Fixed issue #201 
Hey, @sk66641 I have made changes to the styling of buttons. please review it.
Thank you.
> updated css of buttons

- index.html
- style.css
I have created another PRto make it responsive.
Fixed issue #179
For size less than 695 px i moved it to bottom to maintain good appearance
> Added the styling to social icons and changes its placement (Final)

- index.html
- script.js
I have changed the html JavaScript and CSS so that after I click the submit button add time option will be visible and when I click reload it will be invisible as it was previously
#167 
hey @sk66641 please review it
> I have set the changes so that the add time will be visible only after the submit button clicking

- style.css
Changed the styles for the social icons and copyright line for light mode to make it prettier
Fixing issue #176
> Footer and social icons updated

- index.html
- style.css
Hey @sk66641,
issue closes #204 
I have made the following improvements to enhance the visual consistency and user experience on the "About" and "Features" pages:
- **Heading Size Adjustment**: Originally, the headings of both the "About" and "Features" pages were smaller than their respective paragraph contents. I modified the heading sizes to be larger than the content, ensuring a visually correct and hierarchical structure.
- **Color Uniformity:** I matched the colors of both pages to ensure uniformity and a cohesive user experience. Previously, the pages had different colors, which disrupted the visual consistency of the site.
These changes are demonstrated in the Before and After videos I have provided, showing the improvements in heading sizes and color uniformity.
- The Pages Looks …
> Improved Styling of About and Features Pages For Uniformity.

- index.html
- style.css
Made all the changes as promised in issue #244
> Font updates

- index.html
- style.css
I have replaced the facebook logo with the LinkedIn logo and youtube with discord logo
issue no #239
> replace facebook with linkedin logo and discord

- index.html
- style.css
Fix #215 
@sk66641 kindly review the changes.
> Added Neon buttons

- index.html
- style.css
Hey @sk66641 I have created the feedback form, Made Enhancements to Feedback Form | Closes #238
- Recreated the **feedback form**, including its styling and scripts.
- **Responsiveness** in all devices.
- The form now includes **client-side validation** to ensure all required fields are filled before submission, when fields are empty, it display a **"Please Fill out this field"** message.
- After successfully **submitting feedback**, users receive immediate **confirmation with a pop-up message.**
- The **form resets automatically after submission**, providing a clean slate for the next user interaction.
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/101971980/6ca1e2a5-d391-4802-b00a-cdde7c21f845
I request a **level 2 label** for this PR. instead of level 1, based on the …
> Recreated and Made Enhancements to "Feedback Form"

- index.html
- script.js
- style.css
Closes #250 
* On the server side, the side navigation bar appears immediately, resulting in a subpar user experience.
* I have carefully reviewed the HTML, CSS, and JS code, confidently adding the animation property to each element on the side navbar to display in stagger form, enhancing the user experience.
> Smoothness of the side navbar and stagger property for every element

- style.css
Turned Off Text selection in website  #157
Closes #157
@sk66641 I was working on the another issue of this project .. and I got stuff with my exams.. 
@sk66641 Sorry for the delay
So, this PR was submitted later..
@sk66641 Please label this PR under GSSoC
> Turned Off Text selection in website  #157

- index.html
- style.css
Issue number: #270 
I have corrected the styles for Both About and Features pop-up in both Dark and Light mode.
Now, both About and Features have light background for light mode and dark background for dark mode.
I have also fixed close cursor color for dark mode.
Before (Features in dark mode):
After (Features in dark mode):
> Changed the style for About and Features pop-up

- index.html
- script.js
#232 
[Quality reduced due to compression. Actual feature has good image quality*]
> Hover gif added to feature images

- index.html
- script.js
Reverts sk66641/Random-Disco-Light-Simulator#290
> Revert "Hover gif added to feature images"

- about.css
- about.html
- index.html
- script.js
Fixes #278 
A dedicated "About" section has been added and implemented on the webpage. A reference video has also been attached. The theme of the "About" section also matches the main page theme.
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153659573/7d4bdd43-0ebd-40d2-8b2f-13f4dd76bbaf
> Fixes #278 : Added About Page

- features.css
- features.html
- index.html
Fixes #279 
The features page has been implemented. A reference video has been attached for your convenience. In PR #292  we discussed the back button. Instead of adding a back button, I have linked the logo image to redirect to the home page.
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153659573/e70c5d07-2066-408f-8b99-490252cc7832
> Fixes #279 : Added Features Page

- index.html
- script.js
- style.css
Fixes #229 
I have added all the languages google translate offers and i have also made sure that the google translate loader and bar does not come as it was hiding the elements on top of the website also i have made sure when we translate the screen layout does not change
> added the google translate button (more than 50 languages)

- index.html
- script.js
- style.css
I have Improve  the Save Preset and Load Preset Buttons with Cool and Funky Aniamtions and Also Updated the old FeedBack Form to new Elegant Animated Form , I hope You will review my PR and assign this issue to me under GSSOC24.
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/114290748/bbc936f3-36df-483a-80e5-fb87eeae1666
**BEFORE**
**AFTER**
@sk66641
> Improved , Save Preset and Load Preset Buttons with animation And also Improve the FeedBack Form

- 404.html
Fixes #297 
The bug in 404-Error Page has been resolved and now, it redirects to the Home Page.
> Fixes #297 : Fixed bug in 404 Error Page

- about.html
- features.html
- index.html
NavBar will close When Navitem is clicked on mobile devices
Issue No: #280
I added the attribute in the navbar's full-screen navItem and changed the code style
**If it's not good, please assign me again I will do it better**
> [Feat]: NavBar should close When Navitem is clicked on below tablet devices

- style.css
Fixes #317 
i have removed the bar and the reload which arises when we translate the website
> removed the bar and the reload 

- js/script.js
@sk66641 i have fixed the cursor problem now the effects made to cursor will stay consistent even when we scroll
Fixes #299
> Fixed the cursor bug 

- css/features.css
- pages/features.html
Fixes #312 
The Features Page is now responsive for all devices.
> Made Features Page Responsive

- 404.html
- css/404.css
- js/404.js
Hi @sk66641  ,
I hope you're doing well. I've addressed the issue #328  and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?
Also please assign me the level labels according to my PR work.
Best regards,
Tanisha Garg
> modes enabled

- css/style.css
- index.html
- js/script.js
I have made the changes so that now, whenever we press on the social media links, the page does not reload anymore. Instead, a pop-up appears. I made sure to add a fade-in animation to the pop-up to enhance the user experience.
Fixes #332
> Implementation of Pop-up on our social media links to Improve User Experience

- css/style.css
- index.html
- js/script.js
Added a change/edit button to allow modifications while the disco simulator is running. This will enhance functionality and user control.
closes #182
> Adding a change/edit button

- Login/index1.html
- Login/script1.js
- Login/styles1.css
I have made the following changes to the login page 
1. Added Animations: Improved user experience with subtle animations throughout the interface.
2. Incorporated Website Logo: Integrated the  official website logo 
3. Dark Theme Implementation: Updated the theme to a darker color scheme, enhancing visual appeal and readability on black backgrounds. 
4. Form Submission Fix: Resolved an issue where clicking the sign-in button without filling out required fields redirected users, ensuring a smoother interaction.
5. Responsive Design: Implemented responsive design principles to optimize usability across various devices, ensuring seamless access and functionality.
Fixes:  #337
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/92214013/2123b011-2f83-4557-b1b8-f74ac4216834
> Enhancement of the login page

- css/style.css
Edited the nav bar in light mode such that the text remains black but the nav menu is translucent white shade
Fixes:  #(issue no.)
Isuee #324
> Fixing issue #324

- js/top.js
- pages/about.html
- pages/features.html
i have fixed the bug where the back to top button was missing in the about and the features page
Fixes:  #343
> added the back to top button in the features and about pages

- css/feedback.css
- index.html
- pages/feedback.html
Fixes #302 
A dedicated Feedback web page has been implemented. I've attached a video for you to look over.
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153659573/b3cc0c0a-cf3e-4509-a20b-19dbce3096ea
> Added a FeedBack web-page

- index.html
- js/script.js
Reverts sk66641/Random-Disco-Light-Simulator#357
> Revert "Issue#184#2"

- css/style.css
Added stylish scrollbar looks good in darkmode and lightmode.
No need to make changes in mode change in scrollbar.
Fixes:  #344
> New Scrollbar with style

- index.html
- js/script.js
- js/social.js
- pages/about.html
- pages/features.html
- pages/feedback.html
Fixes #369 
i have made a separate javascript file for the pop up so that  it can be implemented in all the pages without causing any new issue
> i have added the social media pop up in all the pages

- css/style.css
- index.html
- js/script.js
Changed the layout of the edit button that shows up during simulation. 
Removed the independant add time button as it is already under the edit dropdown
Revised the functioning of both buttons
Added css styles in both the buttons to match the navbar styles 
Fixes:  #372
> Issue #372

- pages/feedback.html
Added script and for show message prevent to reload page and reset form.
Added thank you message div.
Fixes:  #366
> Thank You message added after submit detail

- Login/index1.html
- Login/styles1.css
in login sign up page the hvering effect was not as per theme and was not looking attractive so changed it to the same as in home page .
Fixes:  #364 
BEFORE : 
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/159682348/6b4c65c4-82a5-4349-bf09-5249985baa44
AFTER : 
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/159682348/dca88f96-9e18-4d6b-b984-e7716cc8ea7e
> add hovering effect in login page social icons 

- Login/index1.html
- Login/script1.js
- package-lock.json
- package.json
I've added confirm password field on sign up page, also an eye icon for password visibility. If both fields are not same, it shows error as in img. And if both fields are dame, it proceeds further.
Fixes:  #347 
Please add gssoc label and do let me know if any changes need to be be made.
> Added Confirm Password

- css/style.css
- index.html
- pages/privacy.html
i have added the privacy policy page and added a link to the footer section of our main page
also i have made sure that the scroll to top button works properly 
and the when we press on the social icons a pop up comes in this website which was missing in the earlier pages
i have made sure all the other features work similar to the main page like the background scroll bar 
Fixes #382 
when we hover on it the color changes i will add the terms and condition at the top right corner of the footer so that looks better
Here is the image of the page i have zoomed out to show the whole page
the back to top button will also be visible when we scroll i runned it in my local machine
> added Privacy policy page 

- index.html
The edit dropdown was not working because the id used to call the dropdown in script.js was not updated in index.html, and due to that the pause feature also did not work properly. All those issues are resolved via this pull request
In addition to pr 379 and issue #372
> Fixed edit and pause issue 

- 404.html
- css/404.css
- css/about.css
- css/features.css
- css/feedback.css
- css/style.css
- index.html
- pages/about.html
- pages/features.html
- pages/feedback.html
Reverts sk66641/Random-Disco-Light-Simulator#392
> Revert "Updated Footer Section"

- css/style.css
- index.html
Fixes:  #305 
I have enhanced the homepage UI based on your requirements, we have  made the following adjustments:
Increased the space between div elements.
Updated the visual design to be more clean and appealing. Ensuring important information is highlighted properly
These changes should make your homepage more visually appealing, align it with modern web standards, and improve user satisfaction and engagement.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
> Enhanced UI and Spacing

- css/style.css
- index.html
- pages/terms.html
I have added the terms and conditions page 
I have also ensured the following things 
1. the back to top button is working properly
2. there is a link to the privacy policy page in the terms and conditions 
3. the pop up appears when the social icons are pressed 
4. The page is responsive and can be accessed in different devices
Fixes:  #381
> Added Responsive and functional terms and conditions page

- css/faq.css
- index.html
- pages/about.html
- pages/faq.html
- pages/features.html
@sk66641 I have added the FAQ Page to the website. Kindly review this.
Fixes:  #386
>  Adding a FAQ Page

- css/style.css
The hover effect is now properly visible on the twitter logo in dark as well as light mode . I have changed the color of the hover on this icon .
Fixes:  #411
> Hover effect is now properly visible on twitter(X) icon and in every mode .

- Login/styles1.css
Now all the social media icons are visible in smaller devices also on the login/signup page
Fixes:  #409
> All the social media icons are now visible in smaller devices on the login/signup page

- css/style.css
- index.html
The font size was getting increased when the language is changed. So I made it constant for all the languages , now it will not get increased.
Fixes:  #375 
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update
> Made the font size constant.

- css/faq.css
- pages/faq.html
Fixes #437 
The UI of the FAQ page is now similar to that of other web pages. Now the container has proper padding in the main container, the background color of the footer is now the same as the background color of the web page and there is a significant space between the container and the footer.
> Improved FAQ Page

- 404.html
- css/404.css
- css/about.css
- css/faq.css
- css/features.css
- css/feedback.css
- css/style.css
- index.html
- pages/about.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
- pages/privacy.html
- pages/terms.html
I have changed the font family of the website to poppins . Now the UI seems good and more attractive . 
Fixes:  #410
> Changed the font family of the website .

- css/style.css
- index.html
- js/script.js
- pages/about.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
Hey @sk66641 and @aditya-bhaumik 
- Issue fixes #448 
I have added the cursor trail effect to the website and its pages 
- It works smooth and fast
- the color is radial gardient of `rgba(73, 232, 247, 0.466)` and `rgba(141, 38, 172, 0.5)`
- added box shadow for glowing effect of mix color `#23bdf5`, `#f523f5` and `#23bdf5`
- Light animation 
https://github.com/user-attachments/assets/8b066bc2-75de-4fc2-9d9d-6c97fbf7b4bd
> Added a "Cursor Trail effect" to the website

- css/contributors.css
- index.html
- pages/contributors.html
Added Contributor page that matches the theme it is responsive working and i make it stylish as i can.
Also add hover effects on contributor cards.
Fixes:  #440
> Added Contributor page

- README.md
hi i have added all the images and made the features section in the readme file better
Fixes:  #407
> Update README.md  features section

- css/style.css
now they are visible in both light and dark mode
Fixes:  #405
> Improve the ui of button in light theme and dark theme

- index.html
- pages/about.html
- pages/contributors.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
Hey @sk66641 
- issue closes #471 
I have fixed the cursor. The trail effect is hidden in mobile view.
https://github.com/user-attachments/assets/b4bc5d18-4765-49aa-8e83-44bc86cad407
> Hide The Trail Effect in Mobile View

- 404.html
Corrected the path to homepage from the 404.html
Fixes:  #466
> Corrected Redirect path

- index.html
> Corrected social media icons positions

- css/style.css
- index.html
Reverts sk66641/Random-Disco-Light-Simulator#458
> Revert "Responsive between 400-300"

- Learn.md
- README.md
GitHub Desktop Contribution Instructions
Fixes:  #442  
Fixes:  #443 
- [] This change requires a documentation update
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
Check [HERE](https://github.com/iamkanhaiyakumar/Random-Disco-Light-Simulator?tab=readme-ov-file#contributing-to-random-disco-light-simulator-)
Chech [HERE](https://github.com/iamkanhaiyakumar/Random-Disco-Light-Simulator/blob/main/Learn.md#installation-and-setup-guide-for-random-disco-light-simulator)
> 📝[Docs]: Adding Installation and Setup Guide

- README.md
added featured in sec
Fixes:  #482 
- [y ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
> Added featured in section

- 404.html
- Login/index1.html
- index.html
- pages/about.html
- pages/contributors.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
- pages/privacy.html
- pages/terms.html
This pull request includes the addition of essential meta tags to all HTML files on the Random Disco Light Simulator site to enhance SEO performance and provide better information to search engines and users.
Fixes:  #464
> Add Required Meta Tags to Improve SEO Performance

- index.html
- js/script.js
- moon.svg
- sun.svg
I changed the mode toggler
Fixes:  #476
https://github.com/user-attachments/assets/0ba79951-56ed-4b4b-815d-0f96b804c8c0
> Updated mode-toggler

- js/script.js
removed chatbot after successful submission. @sk66641 or @aditya-bhaumik please review this pr
Fixes:  #454
> removed chatbot after successful submission

- pages/feedback.html
Fixed the label issue , now correct labels appear on hover of the stars .
Fixes:  #489
> Corrected labels on hover of the stars .

- css/style.css
Just added CSS that give more attractive look in select language filed.
Fixes:  #500
> Style to select language

- css/style.css
- index.html
- js/backToTopBtn.js
- pages/about.html
- pages/contributors.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
- pages/privacy.html
- pages/terms.html
Hey @sk66641 
- issue closes #492 
I have fixed the overlapping chatbot and scroll to top button
> Fixed The Overlapping Chatbot and Scroll to Top Button

- js/script.js
Applied conditions for values in fields for preset to be saved successfully
Fixes:  #517
> Issue #517

- pages/about.html
> Change the Content in About Section 

- pages/feedback.html
Image is fixed in feedback message. 
Fixes:  #528
> Fix Feedback message image

- pages/about.html
- pages/contributors.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
Fixes theme toggle on all pages
Fixes:  #529
> Theme toggle error

- css/backToTopButton.css
- css/style.css
- index.html
- js/backToTopBtn.js
Correctly matched the color theme of the back-to-top button with the background and the view mode.
Fixes:  #525
https://github.com/user-attachments/assets/01bdc188-3210-4d50-a939-bb06e6228f99
> Corrected Back-To-Top button

- pages/about.html
- pages/contributors.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
Reverts sk66641/Random-Disco-Light-Simulator#535
> Revert "Theme toggle error"

- pages/about.html
- pages/contributors.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
Reverts sk66641/Random-Disco-Light-Simulator#542
> Revert "Revert "Theme toggle error""

- css/style.css
Modified the scrollbar so that it matches with UI of website .
Fixes:  #488
> Modified the UI of scrollbar .

- index.html
Now the toggle effect on the home page is working like before.
Fixes:  #545
> Added toggle effect on home page .

- pages/contributors.html
> UI Improvement of contributors page

- css/faq.css
- js/faq.js
- pages/faq.html
**Hide/Show the answer to a question when the question is clicked.**
Fixes:  #(issue no. #487 )
1.    modified the box size of the FAQ page to 700px.
2.    created a faq.js, added functionality that can Hide/Show the answer to a question when the question is clicked.
3.  removed the old faq functionality
> FAQ's changes for better UI

- css/backtohome.css
Add Hover effects on Back to top buttons in all pages.
Fixes:   #558
Hover scale  added
> Added Hover Scale on homebutton

- pages/faq.html
Removed the code snippet that caused it
Fixes:  #539
> Black bar on faq page

- pages/contributors.html
Add Github icon in Contributor page's Card. 
Fixes:  #572
> Added Github Icon

- Login/index1.html
> removed the new logo from the login page 

- Login/index1.html
- index.html
now it is visible in all the pages
Fixes:  #566
> fixed the favicon bug

- Login/index1.html
Added the cursor trail effect that is present on all other pages to the login page
Fixes:  #579
> Added trail cursor on login page

- css/style.css
> Change box color

- pages/features.html
- pages/feedback.html
#Description
Cause for no scroll was a repeated code snip that caused error
Found a similar repeat in features page so also removed it
Fixes:  #576
> Feedback scroll

- index.html
Add Icons in navbar li.
Fixes:  #584
> Added Icons in Sidebar

- pages/contributors.html
Hey @sk66641 and @aditya-bhaumik 
- issue closes #593 
I have fixed the  Bug in Contributors Data Fetching in Contributors Page
https://github.com/user-attachments/assets/7013ef13-2e22-4609-b9a9-cb966ee37bcd
> Fixed the Bug in Contributors Data Fetching in Contributors Page

- pages/terms.html
> Made Minor changes in Terms and conditions 

- css/style.css
> Updated the UI of the language button 

- pages/licensing.html
> fixed the copyright

- css/style.css
> Updated UI Improvement buttons

- css/preloader.css
- js/preloader.js
- js/script.js
- pages/about.html
- pages/contributors.html
- pages/faq.html
- pages/features.html
- pages/feedback.html
- pages/licensing.html
- pages/privacy.html
Fixed particle effect as well as snowflake effect after reforking the repo as suggested, not facing that error in this pr, please confirm
Fixes:  #591
> Re: particle effect

- pages/terms.html
Fixes:  #(issue no.)
Before
After:
> fixed the link color 

- css/about.css
- css/features.css
- css/style.css
Corrected all the mentioned ppages
Fixes:  #526
> Corrected multiple pages

- pages/privacy.html
- pages/terms.html
Made the date's font-color black in light mode, and retained as it is in the dark mode 
Fixes:  #619
> Made text visible

- Login/index1.html
- css/style.css
Added preloader on sign up page
Fixes:  #603
> preloader on signup page

- pages/feedback.html
> fixed the star bug

- pages/licensing.html
> removed unused navbar code

- index.html
- js/script.js
> Updated the Light Pattern Options In website

- css/faq.css
- pages/faq.html
Changed light mode styles as well as dark mode styles
Fixes:  #577
> Faq enhancement

- index.html
- pages/testimonials.html
> Added testimonials

- pages/about.html
> added missing data in the input

- pages/about.html
- pages/contributors.html
- pages/features.html
- pages/feedback.html
these codes were making the code unnessarily big i fixed it 
Fixes:  #639
> Removing unused code and extra spaces for all pages
